In [ ]:
import pandas as pd

In [8]:
#Conjunto de datos
datos = {
    "usuario" : ["Ana", "Luis", "Martha", "Carolina", "Sofia", "Pedro", "Elena", "Diego"],
    "edad" : [22,35,28,40,19,31,26,45],
    "ciudad" : ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancún", "Merida", "Tijuana", "Yucatan"],
    "compras_realizadas" : [5,12,3,29,1,7,4,15],
    "activo" : [True, False, True, True, False, True, False, True],
    "fecha_registro" : ["2026-01-10", "2026-01-12", "2025-01-13", "2025-01-20", "2026-02-10", "2026-01-13", "2026-01-25", "2026-01-12"],
}

In [12]:
#Convertir a DataFrame
df = pd.DataFrame(datos)

In [13]:
print(df)

    usuario  edad       ciudad  compras_realizadas  activo fecha_registro
0       Ana    22         CDMX                   5    True     2026-01-10
1      Luis    35    Monterrey                  12   False     2026-01-12
2    Martha    28  Guadalajara                   3    True     2025-01-13
3  Carolina    40       Puebla                  29    True     2025-01-20
4     Sofia    19       Cancún                   1   False     2026-02-10
5     Pedro    31       Merida                   7    True     2026-01-13
6     Elena    26      Tijuana                   4   False     2026-01-25
7     Diego    45      Yucatan                  15    True     2026-01-12

In [15]:
#Imprime los primeros 5 y si se pasa un parametro, imprimira N (N)
df.head(2)

  usuario  edad     ciudad  compras_realizadas  activo fecha_registro
0     Ana    22       CDMX                   5    True     2026-01-10
1    Luis    35  Monterrey                  12   False     2026-01-12

In [16]:
#Crear un DataFrame con 1000000 de registros
cantidad = 1000000

In [17]:
import random

In [19]:
#Datos aleatorios
nombres = ["Ana", "Luis", "Martha", "Carolina", "Sofia", "Pedro", "Elena", "Diego"]
ciudades = ["CDMX", "Monterrey", "Guadalajara", "Puebla", "Cancún", "Merida", "Tijuana", "Yucatan"]
categorias = ["Tecnología", "Ropa", "Hogar", "Videojuegos", "Deportes", "Calzado", "Formal", "Deportivo"]

In [20]:
#Creación del DataFrame
dfMillon = pd.DataFrame({
    "nombre" : [random.choice(nombres) for _ in range(cantidad)],
    "edad" : [random.randint(18, 70) for _ in range(cantidad)],
    "salario" : [random.uniform(5000, 50000) for _ in range(cantidad)],
    "activo" : [random.choice([True, False]) for _ in range(cantidad)],
    "ciudad" : [random.choice(ciudades) for _ in range(cantidad)],
    "categoria" : [random.choice(categorias) for _ in range(cantidad)],
    "anio_registro" : [random.randint(2020, 2026) for _ in range(cantidad)]
})

In [22]:
dfMillon.shape

(1000000, 7)

In [23]:
dfMillon.dtypes

nombre            object
edad               int64
salario          float64
activo              bool
ciudad            object
categoria         object
anio_registro      int64
dtype: object

In [25]:
dfMillon.memory_usage(deep=True)

Index                  132
nombre           128000000
edad               8000000
salario            8000000
activo             1000000
ciudad           128000000
categoria        128000000
anio_registro      8000000
dtype: int64

In [26]:
dfMillon.memory_usage(deep=True).sum() / 1024**2

np.float64(390.052921295166)